/* MijnSerenity 8.20.5 — ChatGPT geïntegreerd in Start */
(()=>{
'use strict';
if(window.__msChatGPT8205)return;window.__msChatGPT8205=true;
/* Voorkom dat oude Captain-lagen opnieuw opbouwen. */
window.__msCaptainAi8204=true;window.__msCaptainAi71814=true;window.__msDashboardCaptainSearch71832=true;window.__msCaptainAiPro8204=true;
const $=id=>document.getElementById(id),clean=v=>String(v??'').trim(),num=v=>{const m=clean(v).replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null};
const HKEY='mijnserenity-chatgpt-8205';let recorder=null,chunks=[],stream=null,audio=null;
function history(){try{const h=JSON.parse(sessionStorage.getItem(HKEY)||'[]');return Array.isArray(h)?h.slice(-12):[]}catch{return[]}}
function save(h){try{sessionStorage.setItem(HKEY,JSON.stringify(h.slice(-12)))}catch{}}
function add(role,content){const h=history();h.push({role,content:clean(content).slice(0,2200)});save(h);renderHistory()}
function txt(id){return clean($(id)?.textContent)}
function live(){try{return window.liveNavState||{}}catch{return{}}}
function tech(){try{if(typeof technicalStateCache!=='undefined'&&technicalStateCache)return technicalStateCache;if(typeof readTechnicalLocalState==='function')return readTechnicalLocalState()||{}}catch{}return{}}
function context(){const n=live(),t=tech(),w=n.weather||{};return{app_build:window.MIJSERENITY_BUILD||null,boat:{name:'Serenity',type:'Vri-Jon Contessa 37',length_m:11.2},navigation:{status:n.status??null,speed_kmh:num(n.currentSpeedKmh??n.speedKmh??txt('mg-speed')),depth_m:num(n.depthM??n.depth??txt('mg-depth')),rpm:num(n.rpm??n.engineRpm??txt('mg-rpm')),heading_deg:num(n.heading??n.course),gps_status:txt('mgGps')||null,wind_kmh:num(w.windSpeed??w.windKmh),wind_direction:w.windDirection??w.windDir??null,temperature_c:num(w.temperature??w.temp),condition:w.condition??w.summary??null},technical:{house_voltage:num(t.houseVoltage??txt('mgVolt')),house_soc:num(t.houseSoc??t.soc??txt('mgSoc')),house_current_a:num(t.houseCurrent??t.current??txt('mgAmp')),start_voltage:num(t.startVoltage??txt('mgStartV')),shore_power:t.shorePower??txt('mgShore')??null,solar_w:num(t.solarPower??t.pvPower??txt('mgSolar')),water_pct:num(t.waterPct??txt('mg-water')),fuel_pct:num(t.fuelPct??txt('mg-fuel'))}}}
function removeCaptain(){document.querySelectorAll('#msDashboardCaptainSearch,.captain-command-center,.captain-strip').forEach(x=>x.remove());document.querySelectorAll('style[id^="msCaptain"],style[id*="CaptainAi"],style[id*="CaptainAI"]').forEach(x=>x.remove())}
function style(){if($('msChatGPTStyle8205'))return;const s=document.createElement('style');s.id='msChatGPTStyle8205';s.textContent=`
#msChatGPT{grid-column:1/-1;display:grid;gap:12px;width:100%;box-sizing:border-box;padding:15px;border:1px solid rgba(79,205,255,.30);border-radius:20px;background:linear-gradient(145deg,rgba(5,30,48,.96),rgba(7,38,57,.92));box-shadow:0 10px 30px rgba(0,0,0,.16)}
#msChatGPT .cg-head{display:flex;align-items:center;gap:10px}.cg-logo{width:36px;height:36px;display:grid;place-items:center;border-radius:12px;background:rgba(255,255,255,.08);font-size:20px}.cg-head h3{margin:0;color:#fff;font-size:18px}.cg-head small{margin-left:auto;color:#84ddff;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}
.cg-history{display:grid;gap:9px;max-height:320px;overflow:auto;padding:2px}.cg-empty{padding:12px;color:#9eb5c3;font-size:12px;line-height:1.45}.cg-msg{max-width:88%;padding:10px 12px;border-radius:14px;color:#eef9ff;font-size:13px;line-height:1.45;white-space:pre-wrap}.cg-msg.user{justify-self:end;background:rgba(42,151,199,.26);border:1px solid rgba(88,208,255,.25)}.cg-msg.assistant{justify-self:start;background:rgba(0,15,27,.62);border:1px solid rgba(255,255,255,.08)}
.cg-form{display:grid;grid-template-columns:minmax(0,1fr) 50px;gap:8px}.cg-input{min-width:0;height:50px;border:1px solid rgba(119,180,206,.36);border-radius:15px;background:rgba(0,15,27,.78);color:#fff;padding:0 14px;font:inherit;font-size:15px;outline:none}.cg-input:focus{border-color:rgba(86,210,255,.7);box-shadow:0 0 0 3px rgba(66,196,255,.1)}.cg-send{height:50px;border:1px solid rgba(83,211,255,.38);border-radius:15px;background:rgba(34,155,201,.24);color:#fff;font-size:18px;font-weight:900}
.cg-tools{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.cg-tools button{height:38px;padding:0 12px;border:1px solid rgba(105,211,245,.22);border-radius:12px;background:rgba(5,31,47,.86);color:#e9faff;font-size:12px;font-weight:800}.cg-tools button.recording{background:rgba(255,79,91,.18);border-color:rgba(255,103,112,.6)}.cg-tools span{color:#8fa9b7;font-size:10px}.cg-thinking{color:#9eb5c3;font-size:12px;padding:4px 2px}.cg-error{color:#ffb9b9;font-size:12px;padding:8px 10px;border-radius:10px;background:rgba(92,20,27,.24)}
@media(max-width:560px){#msChatGPT{padding:13px;border-radius:18px}.cg-history{max-height:280px}.cg-msg{max-width:94%}.cg-tools button{flex:1 1 auto}.cg-tools span{width:100%}}
`;document.head.appendChild(s)}
function renderHistory(){const box=$('msChatGPTHistory');if(!box)return;const h=history();box.innerHTML=h.length?h.map(x=>`<div class="cg-msg ${x.role==='assistant'?'assistant':'user'}"></div>`).join(''):'<div class="cg-empty">Stel ChatGPT iets over MijnSerenity, de boot, techniek, route of gewoon een algemene vraag.</div>';if(h.length){[...box.children].forEach((el,i)=>el.textContent=h[i].content);box.scrollTop=box.scrollHeight}}
function setState(text,kind='thinking'){const el=$('msChatGPTState');if(!el)return;el.className=kind==='error'?'cg-error':'cg-thinking';el.textContent=text||''}
async function ask(message){const q=clean(message);if(q.length<2)return;add('user',q);setState('ChatGPT denkt mee…');const input=$('msChatGPTInput');if(input)input.value='';try{const h=history().filter(x=>x.content!==q||x.role!=='user').slice(-10);const r=await fetch('/.netlify/functions/chatgpt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,history:h,context:context()})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'ChatGPT is niet bereikbaar.');add('assistant',data.answer||'');setState('')}catch(e){setState(clean(e?.message)||'ChatGPT is tijdelijk niet bereikbaar.','error')}}
function base64(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||'').split(',')[1]||'');r.onerror=rej;r.readAsDataURL(blob)})}
async function startMic(){const b=$('msChatGPTMic');if(recorder&&recorder.state==='recording'){recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia){setState('Microfoon wordt op dit apparaat niet ondersteund.','error');return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];const type=MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':'audio/mp4';recorder=new MediaRecorder(stream,{mimeType:type});recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};recorder.onstop=async()=>{b?.classList.remove('recording');if(b)b.textContent='🎙️ Spreek';stream?.getTracks().forEach(t=>t.stop());setState('Spraak wordt omgezet naar tekst…');try{const blob=new Blob(chunks,{type:recorder.mimeType});const audio64=await base64(blob);const r=await fetch('/.netlify/functions/chatgpt-transcribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audio:audio64,mimeType:blob.type})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Transcriptie mislukt.');const q=clean(data.text);if(!q)throw new Error('Ik kon geen spraak herkennen.');const i=$('msChatGPTInput');if(i)i.value=q;setState('');await ask(q)}catch(e){setState(clean(e?.message),'error')}};recorder.start();b?.classList.add('recording');if(b)b.textContent='⏹ Stop';setState('Ik luister…');setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},30000)}catch(e){setState('Geef Safari microfoontoegang om te kunnen inspreken.','error')}}
async function speak(){const h=history();const last=[...h].reverse().find(x=>x.role==='assistant')?.content;if(!last)return;setState('Audio wordt gemaakt…');try{const r=await fetch('/.netlify/functions/chatgpt-speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:last})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Voorlezen mislukt.');audio?.pause?.();audio=new Audio(`data:${data.mimeType||'audio/mpeg'};base64,${data.audio}`);await audio.play();setState('')}catch(e){setState(clean(e?.message),'error')}}
function build(){removeCaptain();style();if($('msChatGPT'))return true;const grid=$('msMarineGlass')?.querySelector('.mg-grid');if(!grid)return false;const card=document.createElement('section');card.id='msChatGPT';card.innerHTML=`<div class="cg-head"><div class="cg-logo">◉</div><h3>ChatGPT</h3><small>MijnSerenity + OpenAI</small></div><div id="msChatGPTHistory" class="cg-history"></div><form id="msChatGPTForm" class="cg-form" autocomplete="off"><input id="msChatGPTInput" class="cg-input" type="search" maxlength="1800" placeholder="Vraag ChatGPT iets…" aria-label="Vraag aan ChatGPT"><button class="cg-send" type="submit" aria-label="Verstuur">➤</button></form><div class="cg-tools"><button id="msChatGPTMic" type="button">🎙️ Spreek</button><button id="msChatGPTSpeak" type="button">🔊 Voorlezen</button><button id="msChatGPTNew" type="button">＋ Nieuw gesprek</button><span>ChatGPT kan actuele MijnSerenity-data meenemen wanneer dat relevant is.</span></div><div id="msChatGPTState"></div>`;const map=grid.querySelector('.mg-map');if(map)map.insertAdjacentElement('afterend',card);else grid.prepend(card);card.querySelector('#msChatGPTForm')?.addEventListener('submit',e=>{e.preventDefault();ask($('msChatGPTInput')?.value)});$('msChatGPTMic')?.addEventListener('click',startMic);$('msChatGPTSpeak')?.addEventListener('click',speak);$('msChatGPTNew')?.addEventListener('click',()=>{save([]);renderHistory();setState('');$('msChatGPTInput')?.focus()});renderHistory();return true}
function boot(){removeCaptain();let tries=0;const t=setInterval(()=>{tries++;if(build()||tries>40)clearInterval(t)},250);window.addEventListener('mijnserenity:dashboard-ready',()=>setTimeout(build,50),{passive:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)build()},{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();