import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const VRM_BASE="https://vrmapi.victronenergy.com/v2/installations";
const DEFAULT_INSTALLATION=1003203;
const ALARM_LABELS:Record<string,string>={
  lowbattery:"Lage accuspanning",lowvoltage:"Lage accuspanning",highvoltage:"Hoge accuspanning",
  lowsoc:"Lage acculading",lowstartervoltage:"Startaccu spanning laag",highstartervoltage:"Startaccu spanning hoog",
  hightemperature:"Hoge temperatuur",lowtemperature:"Lage temperatuur",overload:"Omvormer overbelast",
  highdccurrent:"Hoge DC-stroom",ripple:"Te hoge DC-rimpel",gridlost:"Walstroom/netspanning weg",
  temperaturesensor:"Temperatuursensor alarm",voltagesensor:"Spanningssensor alarm"
};
const FLUID_NAMES:Record<number,string>={0:"Fuel",1:"Fresh water",2:"Waste water",3:"Live well",4:"Oil",5:"Black water",6:"Gasoline",7:"Diesel",8:"LPG",9:"LNG",10:"Hydraulic oil",11:"Raw water"};

function supabaseUrl(){return String(Deno.env.get("SUPABASE_URL")||"")}
function serviceKey(){return String(Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"")}
function serviceHeaders(extra:Record<string,string>={}){const key=serviceKey();return {Authorization:`Bearer ${key}`,apikey:key,Accept:"application/json",...extra}}
function finite(v:any){return v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v))}
function num(v:any){return finite(v)?Number(v):null}
function rowValue(row:any){for(const v of [row?.valueFloat,row?.rawValue,row?.valueFormattedValueOnly,row?.value])if(finite(v))return Number(v);return null}
function rowPath(row:any){return String(row?.dbusPath||"").trim().toLowerCase()}
function rowText(row:any){return [row?.dataAttributeName,row?.description,row?.dbusPath,row?.dbusServiceType,row?.productName].filter(Boolean).join(" ").toLowerCase()}
function rowString(row:any){for(const v of [row?.rawValue,row?.value,row?.formattedValue,row?.valueFormatted,row?.valueFormattedValueOnly])if(typeof v==="string"&&v.trim())return v.trim();return ""}
function walkRows(value:any,out:any[]=[]){if(!value||typeof value!=="object")return out;if(!Array.isArray(value)&&("dbusPath" in value||"dataAttributeName" in value||"instance" in value))out.push(value);if(Array.isArray(value))for(const item of value)walkRows(item,out);else for(const item of Object.values(value))walkRows(item,out);return out}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function rpc(name:string,body:Record<string,unknown>){const r=await fetch(`${supabaseUrl()}/rest/v1/rpc/${name}`,{method:"POST",headers:serviceHeaders({"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(`${name}_${r.status}:${await r.text()}`);return await r.json().catch(()=>null)}
async function rest(path:string){const r=await fetch(`${supabaseUrl()}/rest/v1/${path}`,{headers:serviceHeaders()});if(!r.ok)throw new Error(`rest_${r.status}:${await r.text()}`);return await r.json().catch(()=>null)}
async function vrmRows(installationId:number,token:string){const c=new AbortController(),timer=setTimeout(()=>c.abort(),18000);try{const r=await fetch(`${VRM_BASE}/${installationId}/diagnostics?count=1000`,{headers:{"X-Authorization":`Token ${token.replace(/^Token\s+/i,"")}`,Accept:"application/json"},signal:c.signal});const b=await r.json().catch(()=>null);if(!r.ok||b?.success===false)throw new Error(`vrm_${r.status}`);return walkRows(b)}finally{clearTimeout(timer)}}

function metric(row:any){return row?{value:rowValue(row),path:String(row?.dbusPath||""),name:String(row?.dataAttributeName||row?.description||""),instance:num(row?.instance)}:null}
function tankGroups(rows:any[]){const groups=new Map<string,any[]>();const paths=new Set(["/level","/fluidtype","/capacity","/remaining","/customname","/productname","/status","/standard"]);for(const row of rows){const path=rowPath(row),service=String(row?.dbusServiceType||"").toLowerCase();if(!service.includes("tank")&&!paths.has(path))continue;const instance=num(row?.instance);if(instance===null)continue;const key=String(instance);if(!groups.has(key))groups.set(key,[]);groups.get(key)!.push(row)}return [...groups.values()]}
function tankFromGroup(group:any[]){const find=(path:string,required=false)=>group.find(r=>rowPath(r)===path&&(!required||rowValue(r)!==null));const levelRow=find("/level",true),fluidRow=find("/fluidtype"),statusRow=find("/status"),capacityRow=find("/capacity",true),remainingRow=find("/remaining",true),nameRow=find("/customname")||find("/productname");const raw=rowValue(levelRow),fluid=rowValue(fluidRow),status=rowValue(statusRow);if(raw===null||raw<0||raw>100)return null;const identity=group.map(r=>`${rowText(r)} ${rowString(r)}`).join(" ").toLowerCase();const cap=rowValue(capacityRow),rem=rowValue(remainingRow);return {levelPct:Math.round(raw*10)/10,fluidType:fluid,fluidName:fluid===null?null:(FLUID_NAMES[fluid]||`Type ${fluid}`),status,instance:num(levelRow?.instance??fluidRow?.instance??group[0]?.instance),name:rowString(nameRow)||String(group[0]?.productName||"")||"Tank",identity,capacityLiters:cap===null?null:Math.round(cap*1000),remainingLiters:rem===null?null:Math.round(rem*1000),sourceMetrics:{level:metric(levelRow),fluidType:metric(fluidRow),status:metric(statusRow)}}}
function tankScore(t:any,type:string){if(!t)return -9999;const id=t.identity||"";let s=0;if(t.status===0||t.status===null)s+=80;else s-=500;if(type==="water"){if(t.fluidType===1)s+=1600;if(/fresh\s*water|freshwater|drinkwater|zoetwater/.test(id))s+=900;if([0,5,6,7].includes(t.fluidType))s-=1200}else if(type==="fuel"){if(t.fluidType===7)s+=1600;if(t.fluidType===0)s+=1200;if(/diesel/.test(id))s+=900;else if(/brandstof|fuel/.test(id))s+=650;if([1,2,5].includes(t.fluidType))s-=900}else if(type==="waste"){if(t.fluidType===5)s+=1600;if(t.fluidType===2)s+=1000;if(/black\s*water|zwartwater|sewage|riool/.test(id))s+=900;else if(/waste\s*water|wastewater|afvalwater|vuilwater/.test(id))s+=600;if([0,1,6,7].includes(t.fluidType))s-=1000}return s}
function readTanks(rows:any[]){const all=tankGroups(rows).map(tankFromGroup).filter(Boolean),used=new Set<number>(),result:any={water:null,fuel:null,waste:null,all:[]};for(const type of ["fuel","water","waste"]){const ranked=all.map((tank:any)=>({tank,score:tankScore(tank,type)})).filter((x:any)=>x.score>200&&!used.has(x.tank.instance)).sort((a:any,b:any)=>b.score-a.score);if(ranked[0]){result[type]=ranked[0].tank;used.add(ranked[0].tank.instance)}}result.all=all.map(({identity,...safe}:any)=>safe);return result}
function readAlarms(rows:any[]){const inactive=/^(|0|off|ok|no alarm|geen alarm|inactive|false)$/i;return rows.filter(r=>rowPath(r).startsWith("/alarms/")).filter(r=>{const n=rowValue(r);if(n!==null)return n!==0;return !inactive.test(rowString(r))}).slice(0,30).map(r=>{const key=(rowPath(r).split("/").filter(Boolean).pop()||"alarm").replace(/[^a-z0-9]/g,"");const warning=/gridlost/.test(key);return {code:`victron_${key}`,key,level:warning?"warning":"critical",title:ALARM_LABELS[key]||String(r?.dataAttributeName||r?.description||"Victron alarm"),path:String(r?.dbusPath||""),value:rowValue(r),formatted:rowString(r)}})}
function safeTank(t:any){if(!t)return null;const {identity,...safe}=t;return safe}

async function syncMonitor(m:any){const sampledAt=new Date().toISOString();const token=await rpc("get_serenity_monitor_vrm_token",{p_monitor_id:m.id});if(typeof token!=="string"||token.length<10)throw new Error("vrm_token_missing");const rows=await vrmRows(Number(m.installation_id||DEFAULT_INSTALLATION),token);const tanks=readTanks(rows),alarms=readAlarms(rows);const patch:any={victronTankSampledAt:sampledAt,victronAlarmSampledAt:sampledAt,victronAlarmCount:alarms.length,victronAlarmLevel:alarms.some((a:any)=>a.level==="critical")?"critical":alarms.length?"warning":"good",victronAlarms:alarms,victronTanks:{water:safeTank(tanks.water),fuel:safeTank(tanks.fuel),waste:safeTank(tanks.waste)},victronWaterAvailable:Boolean(tanks.water),victronFuelAvailable:Boolean(tanks.fuel),victronWasteAvailable:Boolean(tanks.waste)};if(tanks.water&&(tanks.water.status===null||tanks.water.status===0))patch.waterPct=tanks.water.levelPct;if(tanks.fuel&&(tanks.fuel.status===null||tanks.fuel.status===0))patch.fuelPct=tanks.fuel.levelPct;if(tanks.waste&&(tanks.waste.status===null||tanks.waste.status===0))patch.wastePct=tanks.waste.levelPct;await rpc("merge_technical_state_patch",{p_boat_id:m.boat_id,p_patch:patch});return {boatId:m.boat_id,installationId:Number(m.installation_id||DEFAULT_INSTALLATION),water:tanks.water?.levelPct??null,fuel:tanks.fuel?.levelPct??null,waste:tanks.waste?.levelPct??null,alarms:alarms.length,rowCount:rows.length}}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response(JSON.stringify({success:false,error:"POST required"}),{status:405,headers:{"Content-Type":"application/json"}});try{const expected=await rpc("get_serenity_server_secret",{p_name:"serenity_push_cron_secret"});const provided=String(req.headers.get("x-serenity-cron")||"");if(typeof expected!=="string"||!expected||!safeEqual(expected,provided))return new Response(JSON.stringify({success:false,error:"unauthorized"}),{status:401,headers:{"Content-Type":"application/json"}});const monitors=await rest("serenity_alarm_monitors?enabled=eq.true&select=id,boat_id,installation_id")||[];const results=[];for(const m of monitors){try{results.push(await syncMonitor(m))}catch(error:any){results.push({boatId:m.boat_id,error:String(error?.message||error)})}}return new Response(JSON.stringify({success:true,checked:monitors.length,results,sampledAt:new Date().toISOString()}),{status:200,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}catch(error:any){console.error("Victron sync fatal",error);return new Response(JSON.stringify({success:false,error:String(error?.message||error)}),{status:500,headers:{"Content-Type":"application/json"}})}});
